//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etiketler()
        {
            this.Makaleler = new HashSet<Makaleler>();
        }
    
        public int EtiketID { get; set; }
        public string EtiketAd { get; set; }
        public string EtiketAciklama { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makaleler> Makaleler { get; set; }
    }
}
