//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makaleler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makaleler()
        {
            this.Yorumlar = new HashSet<Yorumlar>();
            this.Etiketler = new HashSet<Etiketler>();
        }
    
        public int MakaleID { get; set; }
        public string MakaleBaslik { get; set; }
        public string MakaleOnYazi { get; set; }
        public Nullable<bool> MakaleAktifmi { get; set; }
        public string MakaleIcerik { get; set; }
        public string MakaleKapakResimUrl { get; set; }
        public Nullable<int> MakaleOkunmaSayisi { get; set; }
        public Nullable<System.DateTime> MakaleTarihi { get; set; }
        public int UserID { get; set; }
        public int KategoriID { get; set; }
        public Nullable<int> EtiketID { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiketler> Etiketler { get; set; }
    }
}
