//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumID { get; set; }
        public Nullable<int> MakaleID { get; set; }
        public Nullable<int> CevapID { get; set; }
        public string Eposta { get; set; }
        public string YorumIcerik { get; set; }
        public Nullable<System.DateTime> YorumTarihi { get; set; }
        public Nullable<bool> YorumAktifmi { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual Kullanıcılar Kullanıcılar { get; set; }
        public virtual Makaleler Makaleler { get; set; }
        public virtual YorumCevap YorumCevap { get; set; }
    }
}
